version: 2.1
main: &main
  filters:
    branches:
      only: main
orbs:
  terraform: circleci/terraform@2.0.0
  ghpr: narrativescience/ghpr@1.1.1

parameters:
  tf_organization:
    type: string
    default: ryanwholey
    description: The terraform cloud organization
  tf_workspace_dir:
    type: string
    default: /tmp/terraform-workspace
    description: Workspace location
  tfe_token:
    type: string
    default: $TFE_TOKEN
    description: TFE token

executors:
  docker:
    docker:
      - image: cimg/base:2020.01

jobs:
  setup-terraform-workspace-project:
    executor: docker
    steps:
      - checkout
      - terraform/install:
          terraform_version: 0.14.10
      - run: mkdir -p << parameters.tf_workspace_dir >>
      - run:
          name: Setup terraform project workspace
          command: |
            dir=<< parameters.tf_workspace_dir >>
            mkdir -p "$dir/modules"
            cp -r modules $dir
            cp project-config.tfvars $dir
            cat \<<EOF > "$dir/main.tf"
              data "terraform_remote_state" "secrets" {
                backend = "remote"
                config = {
                  organization = << parameters.tf_organization >>
                  workspaces = {
                    name = "terraform-workspace-manager"
                  }
                  token = "<< parameters.tfe_token >>"
                }
              }
              module "project" {
                source = "./modules/project"
                secrets = data.terraform_remote_state.secrets.outputs.secrets
                config = var.config
              }
              variable "config" {}
              terraform {
                backend "s3" {
                  bucket = "workspace-configs"
                  key    = "terraform-project-1.tfstate"
                  region = "us-west-2"
                }
              }
            EOF
      - terraform/init:
          path: << parameters.tf_workspace_dir >>
      - terraform/plan:
          path: << parameters.tf_workspace_dir >>
          var_file: << parameters.tf_workspace_dir >>/project-config.tfvars
      - persist_to_workspace:
          root: << parameters.tf_workspace_dir >>
          paths:
            - ./*
  apply-terraform-workspace-project:
    executor: docker
    steps:
      - terraform/install:
          terraform_version: 0.14.10
      - attach_workspace: 
          at: << parameters.tf_workspace_dir >>
      - terraform/apply: 
          path: << parameters.tf_workspace_dir >>
          var_file: << parameters.tf_workspace_dir >>/project-config.tfvars
workflows:
  version: 2
  default:
    jobs:
      - setup-terraform-workspace-project:
          context:
            - terraform
      - apply-terraform-workspace-project:
          context:
            - terraform
          requires:
            - setup-terraform-workspace-project
          <<: *main
