version: 2.1
main: &main
  filters:
    branches:
      only: main
orbs:
  terraform: circleci/terraform@2.0.0
executors:
  docker:
    docker:
      - image: cimg/base:2020.01

commands:
  terraform-install:
    - run: 
        command: |
          curl -o /tmp/terraform.zip https://releases.hashicorp.com/terraform/0.14.10/terraform_0.14.10_linux_386.zip
          sudo unzip -d /usr/local/bin /tmp/terraform.zip
jobs:

  setup-terraform-workspace-project:
    executor: docker
    steps:
      - checkout
      - terraform-install
      - run: 
          command: |
            echo 'export TF_PROJECT_DIR=$(mktemp -d)' >> $BASH_ENV
      - run:
          name: Setup terraform project workspace
          command: |
            mkdir -p "$TF_PROJECT_DIR/modules"
            cp -r modules "$TF_PROJECT_DIR"
            cat \<<EOF > "$TF_PROJECT_DIR/main.tf"
              data "terraform_remote_state" "secrets" {
                backend = "remote"
                config = {
                  organization = "ryanwholey"
                  workspaces = {
                    name = "terraform-workspace-manager"
                  }
                }
              }
              module "project" {
                source = "./modules/project"
                secrets = data.terraform_remote_state.secrets.outputs.secrets
                config = var.config
              }
              variable "config" {}
              terraform {
                backend "s3" {
                  bucket = "workspace-configs"
                  key    = "terraform-project-1.tfstate"
                  region = "us-west-2"
                }
              }
            EOF
            
workflows:
  version: 2
  default:
    jobs:
      - setup-terraform-workspace-project:
          context:
            - terraform
