version: 2.1
main: &main
  filters:
    branches:
      only: main
orbs:
  terraform: circleci/terraform@2.0.0
executors:
  docker:
    docker:
      - image: cimg/base:2020.01

# commands:
#   terraform-install:
#     parameters:
#       version:
#         default: '0.14.10'
#         description: |
#           "Terraform CLI version"
#         type: string
#     steps:
#       - run: 
#           command: |
#             curl -o /tmp/terraform.zip https://releases.hashicorp.com/terraform/<< parameters.version >>/terraform_<< parameters.version >>_linux_386.zip
#             sudo unzip -d /usr/local/bin /tmp/terraform.zip
#   terraform-install:
#     steps:
#       - run:
#           command: |
#             terraform init        
jobs:
  setup-terraform-workspace-project:
    executor: docker
    steps:
      - checkout
      - terraform/install:
          terraform_version: 0.14.10
      - run: 
          command: |
            mkdir -p /tmp/terraform-workspace
            echo 'export TF_PROJECT_DIR=/tmp/terraform-workspace' >> $BASH_ENV
      - run:
          name: Setup terraform project workspace
          command: |
            mkdir -p "$TF_PROJECT_DIR/modules"
            cp -r modules "$TF_PROJECT_DIR"
            cat \<<EOF > "$TF_PROJECT_DIR/main.tf"
              data "terraform_remote_state" "secrets" {
                backend = "remote"
                config = {
                  organization = "ryanwholey"
                  workspaces = {
                    name = "terraform-workspace-manager"
                  }
                }
              }
              module "project" {
                source = "./modules/project"
                secrets = data.terraform_remote_state.secrets.outputs.secrets
                config = var.config
              }
              variable "config" {}
              terraform {
                backend "s3" {
                  bucket = "workspace-configs"
                  key    = "terraform-project-1.tfstate"
                  region = "us-west-2"
                }
              }
            EOF
            
      - terraform/init:
          path: /tmp/terraform-workspace
workflows:
  version: 2
  default:
    jobs:
      - setup-terraform-workspace-project:
          context:
            - terraform
