name: Terraform Workspace

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  terraform-workspace:
    name: Terraform workspace
    runs-on: ubuntu-latest
    env:
      AWS_KEY_ID: ${{ secrets.AWS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      TFE_TOKEN: ${{ secrets.TFE_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
      - name: Apply
        run: |
          dir=$(mktemp -d)
          mkdir -p "$dir/modules"
          cp -r modules "$dir"
          cat << EOF > "$dir/main.tf"
            data "terraform_remote_state" "secrets" {
              backend = "remote"
              config = {
                organization = "ryanwholey"

                workspaces = {
                  name = "terraform-workspace-manager"
                }
              }
            }

            module "project" {
              source = "./modules/project"

              secrets = data.terraform_remote_state.secrets.outputs.secrets
              config = var.config
            }

            variable "config" {}

            terraform {
              backend "s3" {
                bucket = "workspace-configs"
                key    = "terraform-project-1.tfstate"
                region = "us-west-2"
              }
            }
          EOF
          cp project-config.tfvars $dir
          cd $dir
          cat << EOF > $dir/.terraformrc
          credentials "app.terraform.io" {
            token = "${{ secrets.TFE_TOKEN }}"
          }
          EOF
          terraform init -backend-config="access_key=${{ secrets.AWS_KEY_ID }}" -backend-config="secret_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}" -backend-config="region=us-west-2"
          terraform apply -auto-approve -var-file project-config.tfvars
